### PR TITLE
GAKeyOverrider: Add Xperia 1 III support

### PR DESCRIPTION
**Pull request by ldzhjn**
GAKeyOverrider: Add Xperia 1 III support

### CODE REVIEW

**Comment by ivaniskandar** [comment]
Is this proven to work?

**Comment by ldzhjn** [comment]
All the model numbers except my own is from Google.
I believe these are all correct.

**Comment by ivaniskandar** [comment]
I mean it's possible that the method to detect assistant button doesn't work on this device, though 10 III is confirmed working so I guess I'll merge this one. Please confirm if it works with the next canary build. Thanks!

**Comment by ldzhjn** [comment]
Tested it on my Xperia 1 iii, it didn't work.
MacroDroid works though.

**Pull request merged**
