### PR TITLE
Added detection of GA button press when Google isn't set as default assistant in settings.

### PR DESCRIPTION
**Pull request by HippityHoppityXD**
Added detection of GA button press when Google isn't set as default assistant in settings.

### CODE REVIEW

**Comment by ivaniskandar** [comment]
I see there's a condition where another assistant activity is showing up, isn't it better if we just change the whole logic to check against the whole Google app then?

**Comment by HippityHoppityXD** [comment]
Checking for the whole google app would trigger the shortcuts every time google would open?
since the only time `assistButtonLastPressedTime` is updated is when google assistant is actually launched. 

this was just a quick fix for me and I thought i may aswell open a pull request incase anyone else wanted it. It may not be ideal but in the 12hours I've been using it the shortcut hasn't triggered so this activity should be exclusive to when you press the GA button without google as the default assistant.

**Comment by ivaniskandar** [comment]
`assistButtonLastPressedTime` is updated when the assistant button is pressed, not when the assistant activity is launched.

There's another assistant activity with the new assistant UI that should be added but I think it's better to change the whole check to do check against the whole google app that's available in `AccessibilityEvent.packageName`.

But doing so will need the handler in `onAccessibilityEvent` to take account of the button press when google app is in foreground. I'd say replace the `assistButtonLastPressedTime` for a boolean `assistButtonHandled`. to make sure we only do the action once every successful button press.

**Comment by HippityHoppityXD** [comment]
I added 2 lines to have the app log the time since a button press.

when the assistant is set to google it is ~300-400ms

_2021-03-08 10:01:12.888 14321-14321/xyz.ivaniskandar.shouko D/GAKeyOverrider$logcatCallback: Assistant Button event detected
2021-03-08 10:01:12.918 14321-14321/xyz.ivaniskandar.shouko D/GAKeyOverrider$muteMusicStream: Muting music stream volume with previous value 0
2021-03-08 10:01:13.237 14321-14321/xyz.ivaniskandar.shouko D/GAKeyOverrider: timeDelta : 348
2021-03-08 10:01:13.237 14321-14321/xyz.ivaniskandar.shouko D/GAKeyOverrider: Opa on foreground after Assist Button event
2021-03-08 10:01:13.238 14321-14321/xyz.ivaniskandar.shouko D/GAKeyOverrider: Back action dispatched, launching action MediaKeyAction(PLAY_PAUSE)_

however when the assistant is not set as google it doesn't update.

_2021-03-08 10:00:49.601 14321-14321/xyz.ivaniskandar.shouko D/GAKeyOverrider: timeDelta : 1615158049601
2021-03-08 10:00:49.602 14321-14321/xyz.ivaniskandar.shouko D/GAKeyOverrider: Opa on foreground after Assist Button event
2021-03-08 10:00:49.603 14321-14321/xyz.ivaniskandar.shouko D/GAKeyOverrider: Back action dispatched, launching action MediaKeyAction(PLAY_PAUSE)_

because of this I'm not too sure how to approach a blanket detection of the whole google app without potentially triggering override when using the the default.
I'm not too experiences with this since I've only made basic apps but would it be possible to check the default assistant, with something like 
```
fun getCurrentAssist(context: Context): ComponentName? {
    val setting: String = Settings.Secure.getString(context.contentResolver, "assistant")
    return if (setting != null) {
        ComponentName.unflattenFromString(setting)
    } else null
}
```

and use different conditions dependent on if Google is set as the default assistant.

**Comment by HippityHoppityXD** [comment]
I kept `assistButtonLastPressedTime` but it should be redundant? I left it in just in case.

`assistButtonLastPressedTime` & `assistButtonHandled` should now be triggered when the button is press, even when it is not a Google Assistant.

I feel like my implementation of the handler and other logic is pretty poor, Feel free to close this

**Comment by ivaniskandar** [comment]
Not having Google as the default assistant is covered with b763cccc9c880a1d26faa15b92ba76aecb9f4305 and any Google app activities that shows up after pressing the button is be covered after 4e168094f547250a8a7f45748d29c0ae3161e2f4. Thanks for the heads up on the multiple cases of launched activities!

**Pull request closed without merging**
